<?php
$i407="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/emo/ani/1f407.png";
$i42a="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/emo/ani/1f42a.png";
$i430="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/emo/ani/1f430.png";
$i431="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/emo/ani/1f431.png";
$i432="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/emo/ani/1f432.png";
$i433="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/emo/ani/1f433.png";
$i434="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/emo/ani/1f434.png";
$i435="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/emo/ani/1f435.png";
$i436="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/emo/ani/1f436.png";
$i437="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/emo/ani/1f437.png";
$i438="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/emo/ani/1f438.png";
$i439="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/emo/ani/1f439.png";
$i43a="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/emo/ani/1f43a.png";
$i43b="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/emo/ani/1f43b.png";
$i43c="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/emo/ani/1f43c.png";
$i43e="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/emo/ani/1f43e.png";
$i479="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/emo/ani/1f479.png";
$i47a="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/emo/ani/1f47a.png";
$i47d="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/emo/ani/1f47d.png";
$i480="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/emo/ani/1f480.png";
$i981="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/emo/ani/i981.png";
$rab="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/emo/ani/rab.png";

